---
title: "ETS Model"
author: "Michael Mayor"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fpp)
library(dplyr)
library(tibble)
library(lubridate)
library(TSstudio)
library(xts)
```

```{r}
load(file = "./data/DOGE.Rdata")
```

```{r Clean Data}
dogeparsed$timestamp <- as.Date(dogeparsed$timestamp)
dogeparsed <- dogeparsed[c(1,9)]
doge_xts <- xts(dogeparsed[-1], order.by = dogeparsed$timestamp, frequency = 1)
colnames(doge_xts) <- c("close")
```

```{r}
doge_xts = doge_xts[,1][500:615]
tsdisplay(doge_xts) # As you can see from the ACF, this is not stationary
```

```{r}
tsdisplay(diff(doge_xts)) # After doing differencing, we have a better ACF that shows that we have white noise
```

```{r}
# Implement differencing

diff_doge_xts <- (diff(doge_xts))

# We want to split our data into training and testing

train = doge_xts[,1][1:92]

test = doge_xts[,1][93:116]
```

```{r}
autoplot(doge_xts[-1], main = "Dogecoin", ylab = "USD", xlab = "Time")
```

```{r ETS Model}
fit_ets <- ets(train, lambda = -.2568437)
fc_ets <- forecast(fit_ets, h = length(test))
plot(forecast(fit_ets))
accuracy(fc_ets, test)

checkresiduals(fit_ets)
```


```{r Holt Winters}
doge_ts <- ts(doge_xts)
doge_train <- ts(train)

fit1 <- holt(doge_train, h = length(test), lambda = -.2568437) #additive Holt-Winters method
fit2 <- holt(doge_train, seasonal="multiplicative", h = length(test), lambda = -.2568437) #multiplicative Holt-Winters method
fit3 <- holt(doge_train, damped=TRUE, h = length(test), lambda = -.2568437) #additive Holt-Winter method with damped trend 
fit4 <- holt(doge_train, seasonal="multiplicative", damped=TRUE, h = length(test), lambda = -.2568437) #multiplicative Holt-Winter method with damped trend 

autoplot(window(doge_ts, end = 92)) +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(fit1$mean, series = "Additive HW", PI = FALSE) +
  autolayer(fit2$mean, series = "Multiplicative HW", PI = FALSE) +
  autolayer(fit3$mean, series = "Additive HW - Damped", PI = FALSE) +
  autolayer(fit4$mean, series = "Multiplicative HW - Damped", PI = FALSE)

```

```{r}
checkresiduals(fit1)
checkresiduals(fit2)
checkresiduals(fit3)
checkresiduals(fit4)
```

```{r}
save(doge_xts, file = "doge_xts.Rdata")
```

