---
title: "DOGE_Coin"
author: "Shivam Patel"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Library}
library(httr)
library(forecast)
library(xts)
library(tseries)
library(fGarch)
```


```{r Pulling data from API}
# API KEY: 0YR02HPT5Z0LVCHN

# doge_test <- GET("https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=DOGE&market=CNY&datatype=csv&apikey=0YR02HPT5Z0LVCHN")

# dogeparsed <- read.delim(text = content(doge_test, as = "text"), sep = ",")
#save(dogeparsed, file = "./data/DOGE.Rdata")
# only uncomment to update the data to the most recent

# Going to use Close Price, USD.
```

Start with a benchmark, and then include the lambda in auto.arima, look at week 3 for this example code
combine week 3 and 4 together
go with the lowest AIC
check residuals


# BEGIN PROJECT

```{r}
load(file = "./data/DOGE.Rdata")
```

```{r Explore Data}
head(dogeparsed)
dogeparsed$timestamp <- as.Date(dogeparsed$timestamp)
str(dogeparsed)
```
```{r Data Cleaning}
dogeparsed <- dogeparsed[c(1,9)]
doge_xts <- xts(dogeparsed[-1], order.by = dogeparsed$timestamp, frequency = 1)
doge_xts <- doge_xts[500:615]
colnames(doge_xts) <- c("close")
```

```{r Plotting}
autoplot(ts(doge_xts), main = "Dogecoin", xlab = "Time", ylab = "USD")
```

```{r Transformation}
BoxCox.lambda(doge_xts)
# -.5 value returned so there is a need for some transformation
# lets run it under the boxcox transformation auto and by manually setting the lamba value
plot(doge_xts)
plot(BoxCox(doge_xts,lambda="auto"))
plot(BoxCox(doge_xts,lambda = -.25))
```

```{r Explore the ACF before and after transformation and differencing}
tsdisplay(doge_xts) # original
tsdisplay(BoxCox(doge_xts, lambda = "auto")) # transformed
tsdisplay(diff(doge_xts)) # differencing
```

Differencing is the way to go.

```{r}
doge_xts_diff <- diff(doge_xts)
```


```{r Splitting the data}
doge_train <- doge_xts[1:92]
doge_test <- doge_xts[,1][93:116]

doge_ts <- ts(doge_xts)
doge_train <- ts(doge_train)

# differenced data
doge_train_diff <- doge_xts_diff[1:92]
doge_test_diff <- doge_xts_diff[93:116]

doge_ts_diff <- ts(doge_xts)
doge_train_diff <- ts(doge_train_diff)
doge_test_diff  <- ts(doge_test_diff)

```

Let's explore some simple forecasting methods

```{r Simple Forecasting Methods}
mean_doge <- meanf(doge_train, h = 24)
naive_doge <- naive(doge_train, h = 24)
snaive_doge <- snaive(doge_train, h = 24)
drift_doge <- rwf(doge_train, h = 24, drift = TRUE)

autoplot(window(doge_ts, end = 92), ylab = "Doge Coin Price") +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(mean_doge, series = "Average Method", PI = FALSE) +
  autolayer(naive_doge, series = "Naive Method", PI = FALSE) +
  autolayer(snaive_doge, series = "Seasonal Naive Method", PI = FALSE) +
  autolayer(drift_doge, series = "Drift Method", PI = FALSE)
# Seasonal Naive and Naive are the same here

# using lamba in functions
mean_doge_l <- meanf(doge_train, h = 24, lambda = -0.2568437)
naive_doge_l <- naive(doge_train, h = 24, lambda = -0.2568437)
snaive_doge_l <- snaive(doge_train, h = 24, lambda = -0.2568437)
drift_doge_l <- rwf(doge_train, h = 24, drift = TRUE, lambda = -0.2568437)

autoplot(window(doge_ts, end = 92), ylab = "Doge Coin Price") +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(mean_doge_l, series = "Average Method", PI = FALSE) +
  autolayer(naive_doge_l, series = "Naive Method", PI = FALSE) +
  autolayer(snaive_doge_l, series = "Seasonal Naive Method", PI = FALSE) +
  autolayer(drift_doge_l, series = "Drift Method", PI = FALSE)
```

```{r Measure Accuracy of Simple Forecasting Methods}
print("Mean")
accuracy(mean_doge, doge_test)
print("Naive")
accuracy(naive_doge, doge_test)
print("Seasonal Naive")
accuracy(snaive_doge, doge_test)
print("Drift Method")
accuracy(drift_doge, doge_test)
```

```{r Measure Accuracy of Simple Forecasting Methods with lambda}
print("Mean")
accuracy(mean_doge_l, doge_test)
print("Naive")
accuracy(naive_doge_l, doge_test)
print("Seasonal Naive")
accuracy(snaive_doge_l, doge_test)
print("Drift Method")
accuracy(drift_doge_l, doge_test)
```

```{r}
checkresiduals(mean_doge)
ggPacf(residuals(mean_doge))

checkresiduals(mean_doge_l)
ggPacf(residuals(mean_doge_l))
```

```{r}
checkresiduals(naive_doge)
ggPacf(residuals(naive_doge))

checkresiduals(naive_doge_l)
ggPacf(residuals(naive_doge_l))
```

```{r}
checkresiduals(snaive_doge)
ggPacf(residuals(snaive_doge))

checkresiduals(snaive_doge_l)
ggPacf(residuals(snaive_doge_l))
```

```{r}
checkresiduals(drift_doge)
ggPacf(residuals(drift_doge))

checkresiduals(drift_doge_l)
ggPacf(residuals(drift_doge_l))
```

```{r ETS Model}
fit_ets <- ets(doge_train, lambda = -.2568437)
fc_ets <- forecast(fit_ets, h = length(doge_test))
plot(forecast(fit_ets))
accuracy(fc_ets, doge_test)

checkresiduals(fit_ets)
```


```{r Holt Winters}
fit1 <- holt(doge_train, h = length(doge_test), lambda = -.2568437) #additive Holt-Winters method
fit2 <- holt(doge_train, seasonal="multiplicative", h = length(doge_test), lambda = -.2568437) #multiplicative Holt-Winters method
fit3 <- holt(doge_train, damped=TRUE, h = length(doge_test), lambda = -.2568437) #additive Holt-Winter method with damped trend 
fit4 <- holt(doge_train, seasonal="multiplicative", damped=TRUE, h = length(doge_test), lambda = -.2568437) #multiplicative Holt-Winter method with damped trend 

autoplot(window(doge_ts, end = 92)) +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(fit1$mean, series = "Additive HW", PI = FALSE) +
  autolayer(fit2$mean, series = "Multiplicative HW", PI = FALSE) +
  autolayer(fit3$mean, series = "Additive HW - Damped", PI = FALSE) +
  autolayer(fit4$mean, series = "Multiplicative HW - Damped", PI = FALSE)

```

```{r}
checkresiduals(fit1)
checkresiduals(fit2)
checkresiduals(fit3)
checkresiduals(fit4)
```

```{r}
accuracy(forecast(fit1), doge_test) # Additive HW Method
accuracy(forecast(fit2), doge_test) # Mult. HW Method
accuracy(forecast(fit3), doge_test) # Add. HW Method Damped
accuracy(forecast(fit4), doge_test) # Mult. HW Method Damped
```

ARIMA Models

```{r ARIMA}
tsdisplay(doge_xts)
tsdisplay(BoxCox(doge_xts, lambda = -0.2568437)) # transformed
```


```{r MA(2)}
arima_ma_2 <- arima(doge_train, order = c(0,0,2))
summary(arima_ma_2)
```


```{r Auto ARIMA}
auto_arima <- auto.arima(doge_train, seasonal = FALSE)
summary(auto_arima)
```


```{r Auto ARIMA (lambda)}
auto_arima_lambda <- auto.arima(doge_train, seasonal = FALSE, lambda = -0.2568437)
summary(auto_arima_lambda)
```


```{r Residuals}
tsdisplay(arima_ma_2$residuals) #Check the residuals
tsdisplay(auto_arima$residuals) #Check the residuals
tsdisplay(auto_arima_lambda$residuals) #Check the residuals
```


```{r Generate Forecast}
fcast_1 <- forecast(arima_ma_2, h = 24)
fcast_2 <- forecast(auto_arima, h = 24)
fcast_3 <- forecast(auto_arima_lambda, h = 24)
```



```{r MA(2) Accuracy}
accuracy(fcast_1, doge_test) # MA(2)
checkresiduals(fcast_1)
```

```{r Auto ARIMA Accuracy}
accuracy(fcast_2, doge_test) # auto arima
checkresiduals(fcast_2)
```


```{r Auto ARIMA (lambda) Accuracy}
accuracy(fcast_3, doge_test) # auto arima, lambda
checkresiduals(fcast_3)
```

```{r Plotting}
autoplot(window(doge_ts, end = 92), ylab = "Doge Coin Price") +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(fcast_1, series = "MA(2)", PI = FALSE) +
  autolayer(fcast_2, series = "Auto ARIMA", PI = FALSE) +
  autolayer(fcast_3, series = "Auto ARIMA (lambda)", PI = FALSE)
```

```{r GARCH Model}
garchm <- garchFit(~arma(2, 1)+garch(1,1), doge_train)
summary(garchm)

# p value > .05 so we fail to reject the null hypothesis, so there is so evidence of any autocorrelation in the residuals. I believe we might be able to conclude there the residuals are acting as white noise.

garch_predict <- predict(garchm, 24)

accuracy(garch_predict$meanForecast, doge_test)

garch_train_predict <- data.frame(doge_train)
garch_predict_mean <- data.frame(garch_predict$meanForecast)
colnames(garch_predict_mean) <- "close"

fcast_garch <- ts(rbind(garch_train_predict, garch_predict_mean))

autoplot(window(doge_ts, end = 92), ylab = "Doge Coin Price") +
  autolayer(window(doge_ts, start = 92), series = "Test Data") +
  autolayer(fcast_1, series = "MA(2)", PI = FALSE) +
  autolayer(fcast_2, series = "Auto ARIMA", PI = FALSE) +
  autolayer(fcast_3, series = "Auto ARIMA (lambda)", PI = FALSE) +
  autolayer(window(fcast_garch, start = 92), series = "GARCH")
```

```{r GARCH Accuracy}
accuracy(garch_predict$meanForecast, window(doge_ts, start = 93)) # auto arima, lambda

```



